config/routes.rb
Rails.application.routes.draw do
  resources :results
  resources :users
  resources :carbs
  resources :vegetables
  resources :proteins

  patch "/sessions/update_view", to: 'sessions#update_view', as: 'reset_session'
  delete "/sessions/logout", to: 'sessions#logout', as: 'logout'
  # get "/sessions", to: "sessions#create", as: "login"
  get "sessions/new", to: "sessions#new", as: "new_login"
  post "/sessions", to: "sessions#create", as: "login"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "/signup", to: "user#new", as: "signup"
  post "/users", to: "users#create", as: "signin"



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/carb.rb
class Carb < ApplicationRecord
    has_many :results
    has_many :users, through: :results

    validates :name, uniqueness: true
end

app/models/protein.rb
class Protein < ApplicationRecord
    has_many :results
    has_many :users, through: :results

    validates :name, uniqueness: true
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  belongs_to :vegetable
  belongs_to :protein
  belongs_to :carb




  # def calculate(calories)
  #   protein_calories = calories / 4 
  #   carb_calories = calories / 4 
  #   vege_calories = calories / 2
  # end

  def protein_gram
    protein = self.protein.cal_per_gram
    protein_calories = self.calories_per_meal / 4 
    cal_gram = protein_calories / protein

    cal_gram
  end

  def carb_gram
    carb = self.carb.cal_per_gram
    carb_calories = self.calories_per_meal / 4 
    cal_gram = carb_calories / carb

    cal_gram
  end

  def vegetable_gram
    vege = self.vegetable.cal_per_gram
    vege_calories = self.calories_per_meal / 2
    cal_gram = vege_calories / vege
    
    cal_gram
  end


end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :results 
    has_many :proteins, through: :results
    has_many :carbs, through: :results
    has_many :vegetables, through: :results

    validates :name, uniqueness: true
    validates :email, uniqueness: true


def calculator
 if self.gender == "Male"
    sum = 66 + (6.3 * self.weight) + (12.9 * self.height) - (6.8 * self.age) + 400
 else
    sum = 655 + (4.3 * self.weight) + (4.7 * self.height) - (4.7 * self.age) + 300
end
sum
end

end

app/models/vegetable.rb
class Vegetable < ApplicationRecord
    has_many :results
    has_many :users, through: :results

    validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :get_user
    before_action :auth_user
  
    def get_user
      # @current_user = User.find(session[:user_id])
      @current_user = User.find_by(id: session[:user_id])
    end 
  
  
    def auth_user
      if @current_user
        # Continue on into app
      else 
        redirect_to new_user_path
      end  
    end 

end

app/controllers/carbs_controller.rb
class CarbsController < ApplicationController
    
      def index
        @carbs = Carb.all
      end
    
      def show
        @carb = Carb.find(params[:id])
        @result = @carb.results.to_a
      end

      def new 
        @carb = Carb.new
      end

    
      def create
        @carb = Carb.create(carb_params)
        redirect_to carb_path(@carb.id)
      end
    
      def update
       @carb = Carb.find(params[:id])
       @carb.update(carb_params)
       redirect_to carb_path(@carb)
      end
    
      def edit
        @carb = Carb.find(params[:id])
      end
    
      def destroy
        @carb = Carb.find(params[:id])
        @carb.destroy
        redirect_to carb_path
      end

      private

      def carb_params
        params.require(:carb).permit(:name, :whole_grain, :cal_per_gram)
      end
end

app/controllers/proteins_controller.rb
class ProteinsController < ApplicationController

    def index
        @proteins = Protein.all
      end
    
      def show

        
        #if session[:view_count] 
         #   session[:view_count] = session[:view_count].to_i + 1
        #else
        #    session[:view_count] = 1
        #end

        @protein = Protein.find(params[:id])
        @result = @protein.results.to_a
      end
    
      def create
        @protein= Protein.create(protein_params)
        redirect_to protein_path(@protein.id)
      end

      def new
          @protein = Protein.new
      end
    
      def update
       @protein= Protein.find(params[:id])
       @protein.update(protein_params)
       redirect_to protein_path(@protein)
      end
    
      def edit
        @protein = Protein.find(params[:id])
      end
    
      def destroy
        @protein = Protein.find(params[:id])
        @protein.destroy
        redirect_to protein_path

      end

      private

      def protein_params
        params.require(:protein).permit(:name, :vegetarian, :cal_per_gram)
      end
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
    def index
        @results = Result.all
    end
    
    def new
        @result = Result.new
    end
    
    def create
        
        @result = Result.create(result_params)
    
       
        redirect_to result_path(@result)
    end
    
    # def edit
    #     @result = Result.find(params[:id])
    # end
    
    # def update
    
    # end
    
    def show
        @result = Result.find(params[:id])
    end
    
    # def destroy
    
    # end

private 

def result_params
    params.require(:result).permit(:user_id, :vegetable_id, :protein_id, :carb_id, :calories_per_meal)
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :auth_user, only: [:new, :create]


    def update_view
        session[:view_count] = 0

        redirect_back fallback_location: proteins_path
    end


  def logout
    session.delete(:user_id)
  end 

  def new 
  end 

  def create 
    @user = User.find_by(name: params[:session][:name])

    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id

      redirect_to user_path(@user.id)
    else
      flash[:error] = "Username or Password is Incorrect"
      redirect_to new_login_path
    end  
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
skip_before_action :auth_user, only: [:new, :create]
  def index
    @users = User.all 
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])

  end

  def create
    @user = User.create(user_params)

    if @user.valid?
      session[:user_id] = @user.id
      redirect_to edit_user_path(@user.id)
    else
      flash[:user_errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
     @user = User.find(params[:id])
     @user.destroy

     redirect_to new_user_path
  end

  private 

  def user_params
    params.require(:user).permit(:name, :age, :gender, :weight, :height, :email, :password)
  end


end

app/controllers/vegetables_controller.rb
class VegetablesController < ApplicationController
    def index
        @vegetables = Vegetable.all
    end
    
    def new
        @vegetable = Vegetable.new
    end
    
    def create
        @vegetable = Vegetable.create(vegetable_params)
        redirect_to vegetable_path(@vegetable.id)
    end
    
    def edit
        @vegetable = Vegetable.find(params[:id])
    end
    
    def update
        @vegetable = Vegetable.find(params[:id])
        @vegetable.update
        redirect_to vegetable_path(@vegetable.id)
    end
    
    def show
        @vegetable = Vegetable.find(params[:id])
        @result = @vegetable.results.to_a            #array of users
    end
    
    def destroy
        @vegetable = Vegetable.find(params[:id])
    end

    private

    def vegetable_params
        params.require(:vegetable).permit(:name, :cal_per_gram)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carbs_helper.rb
module CarbsHelper
end

app/helpers/proteins_helper.rb
module ProteinsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/vegetables_helper.rb
module VegetablesHelper
end

app/views/carbs/index.html.erb
<h1>Carbs</h1>

<% @carbs.each do |u| %>
<%= link_to u.name,  carb_path(u.id) %> <br>
<% end %>    

app/views/carbs/new.html.erb
<h1>Create new carb</h1>

<%= form_for @carb do |p| %>
<%= p.label :name %>
<%= p.text_field :name %>

<%= p.label :cal_per_gram %>
<%= p.number_field :cal_per_gram %>

<%= p.submit %>
<% end %>

app/views/carbs/show.html.erb
<h1>Show carbs</h1>
<h2><%= @carb.name %></h2>
<h3>Calories per gram = <%= @carb.cal_per_gram%></h3>
<h4>Who also tried <%= @carb.name %> : <% @result.each do |r| %>
<%= r.user.name %> <br>
<% end %>
</h4>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HealthyDietApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <ul>
      <li><%= link_to 'Friends', users_path%></li>
     <li><%= link_to 'Proteins', proteins_path%></li>
      <li><%= link_to 'Carbs', carbs_path%></li>
      <li><%= link_to 'Vegetables', vegetables_path %></li>
  

      <% if @current_user %>
        <li class='right'> Welcome <%=  @current_user.name %></li>                    
        <li class='right'><%= link_to "Log-Out", logout_path, method: :delete %></li>
      <% else %>
        <li class='right'><%= link_to 'Sign-up', new_user_path %></li>
        <li class='right'><%= link_to 'Login', new_login_path %></li>
      <% end %>
    </ul>

    <%= yield %>
  </body>
</html>

app/views/proteins/index.html.erb
<h1>Proteins</h1>
<% @proteins.each do |u| %>
<%= link_to u.name,  protein_path(u.id) %> <br>
<% end %>    

app/views/proteins/new.html.erb
<h1>Create new protein</h1>

<%= form_for @protein do |p| %>
<%= p.label :name %>
<%= p.text_field :name %>

<%= p.label :cal_per_gram %>
<%= p.number_field :cal_per_gram %>

<%= p.submit %>
<% end %>

app/views/proteins/show.html.erb
 <% #if session[:view_count].to_i <= 3 %>
<h1>Show proteins</h1>
<h2><%= @protein.name %></h2>
<h3>Calories per gram = <%= @protein.cal_per_gram%></h3>
<h4>Who also tried <%= @protein.name %> : <% @result.each do |r| %>
<%= r.user.name %> <br>
<% end %>
</h4>

app/views/results/index.html.erb
<h1>INDEX results</h1>

app/views/results/new.html.erb
<h3><i>"Think of your plate containing three sections: vegetables, carbs, and proteins. 
    Vegetables should fill half the plate and carb and protein should fill the other half of the plate. 
    Eat a wide variety of vegetables in every color to ensure a range of nutrients".</i></h3>
   

<h2>Please choose form above: </h2>
<h3>
<%= form_for @result do |f| %>
Proteins: <%= f.collection_select :protein_id, Protein.all, :id, :name %> || <i><h5><%= link_to "CUSTOMIZE", new_protein_path(@protein) %></h5></i> <br>
Carbs: <%= f.collection_select :carb_id, Carb.all, :id, :name %> || <i><h5><%= link_to "CUSTOMIZE", new_carb_path(@carb) %></h5> </i> <br>
Vegetable: <%= f.collection_select :vegetable_id, Vegetable.all, :id, :name %> || <i><h5><%= link_to "CUSTOMIZE", new_vegetable_path(@vegetable) %></h5> </i> <br>

<%= f.hidden_field :user_id, value: session[:user_id]%>


<%= f.label :calories_per_meal %>
<%= f.number_field :calories_per_meal %> (500 - 2000)

</h3>
<%= f.submit %>
<% end %>

app/views/results/show.html.erb
<h1>Your meal should look like:</h1>



<p>Protein: <%= @result.protein_gram %></p>

<p>Carb: <%=  @result.carb_gram%></p>

<p>Vegetable: <%=  @result.vegetable_gram%></p>

app/views/users/edit.html.erb
<h1>We need just few more informations: </h1>


<%= form_for @user do |p| %>

<%= p.label :age %>
<%= p.number_field :age %> <br>

<%= p.radio_button(:gender, "Male") %>
<%= p.label(:gender, "Male") %>
<%= p.radio_button(:gender, "Female") %>
<%= p.label(:gender, "Female") %> <br>

<%= p.label :weight %>
<%= p.number_field :weight %> <br>

<%= p.label :height %>
<%= p.number_field :height %> <br><br>

<%= p.submit "Done" %>

<% end %>

app/views/users/index.html.erb
<% #if cookies[:view_count].to_i <= 3 %>

<h2>Find your friends :</h2>
<p>"Having a sense of community <strong>unites us</strong>. Being a part of a community 
    can make us feel as though we are a part of something <strong>greater</strong> than ourselves.<br>
    It can give us opportunities to connect with people, to reach for our <strong>goals</strong>, 
    and makes us feel safe and secure".</p>


    <h3>Check out your friend's calories score, but <mark>please, do not edit not-your profile</mark>, that would end friendship...</h3>


<% @users.each do |u| %>
<p><li><i><%= link_to u.name, user_path(u.id) %> </i><br></li></p>
<% end %>    

app/views/users/new.html.erb
<h1>Create new user</h1>

<% if flash[:user_errors] %>
  <% flash[:user_errors].each do |error| %>
    <p style='color: red;'><%= error %></p>
  <% end %>
<% end %>

<%= form_for @user do |p| %>
<%= p.label :name %>
<%= p.text_field :name %> <br>



<%= p.label :password %>
<%= p.text_field :password %> <br>




<%= p.label :email %>
<%= p.text_field :email %> <br>




<%= p.submit %>

<%= button_to "Back", users_path(@user.id) %> 

<% end %>

app/views/users/show.html.erb
<% if flash[:error] %>
  <h1 style="color: red;"><%= flash[:error] %></h1>
<% end %>
<h1><%= @user.name %></h1>
<h1>Welcome <%= @user.name %>!<br></h1>
<h2><i> Here are some informations about you: </i></h2>

<h3>
Name: <%= @user.name %><br>
Age: <%= @user.age %><br>
Gender: <%= @user.gender %><br>
Weight: <%= @user.weight %><br>
Height: <%= @user.height.round(2) %> </h3>


<p> You need: <%= @user.calculator.round(0) %> calories per day.</p>



<p>Would you like to <%= link_to "EDIT", edit_user_path %> your profile?</p>

<%= link_to "CREATE MY MEAL", new_result_path %> 



<%= button_to "Delete", { action: "destroy", id: @user.id },
                                method: :delete, data: { confirm: "Are you sure?" } %>

app/views/vegetables/index.html.erb
<h1>Index of vege </h1>

<address>Vegetables are important sources of many nutrients, including potassium, dietary fiber, folate (folic acid), vitamin A, and vitamin C. 
    Diets rich in potassium may help to maintain healthy blood pressure. As part of an overall healthy diet, eating foods such as vegetables 
    that are lower in calories per cup instead of some other higher-calorie food may be useful in helping to lower calorie intake.</address>

<% @vegetables.each do |v| %>
<ol><i><%= link_to v.name, vegetable_path(v.id) %> </i><br></ol>
<% end %>

app/views/vegetables/new.html.erb
<h1>New vege!</h1>

<i><h2>"You can add new vegetable if you want, the only information we need is calories per gram!"</h2></i>


<%= form_for @vegetable do |f| %>
<h2><%= f.label :name %>
<%= f.text_field :name %> <br>
<%= f.label :calories_per_gram %>
<%= f.number_field :cal_per_gram %><br>
<%= f.submit "Add Vege" %> </h2>
<% end %>


<h1>Yamm!</h1>

app/views/vegetables/show.html.erb
<h1>Show of vege</h1>

<h2><%= @vegetable.name %></h2>
<h3>Calories per 1g = <%= @vegetable.cal_per_gram %>.</h3>
<h4>Who also tryed <%= @vegetable.name %> : <% @result.each do |r|%>
    <%= r.user.name %><br>
<% end %>
</h4>